# frozen_string_literal: true

# Gemfile for personal-site generated by Quartet

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '~> 2.0'

gem 'rake', '~> 13.0'

gem 'irb', '~> 1.2'
